services:
  drinkflow:
    build: .
    ports:
      - "8080:8000"

    env_file:
    - ./core/.env

    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    command: >
      sh -c "alembic upgrade head && 
      uvicorn core.main:app --host 0.0.0.0 --port 8000"
    restart: unless-stopped
  postgres:
    image: postgres:18.4
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d drinkflow"]

    volumes:
      - postgres_data:/var/lib/postgresql

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
    restart: unless-stopped
  redis:
    image: redis:8.10
    restart: always

  celery:
    build: .

    env_file:
    - ./core/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
      postgres:
        condition: service_healthy

    command: 
      celery -A core.celery_worker worker --loglevel=info
    restart: unless-stopped

  order_consumer:
    build: .

    env_file:
      - ./core/.env

    depends_on:
      rabbitmq:
        condition: service_healthy
      celery:
        condition: service_started

    command: 
      python -m core.messages.order_consumer  
    restart: unless-stopped
volumes:
  postgres_data: