"""add statistic fields for orders

Revision ID: f9990772f12e
Revises: 44efc389e246
Create Date: 2026-08-30 16:48:41.911426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9990772f12e'
down_revision: Union[str, Sequence[str], None] = '44efc389e246'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('item_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('orders', sa.Column('total_price', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'total_price')
    op.drop_column('orders', 'item_count')
    # ### end Alembic commands ###
